### ISSUE TITLE
Get dot on vertical line

### ISSUE THREAD

**Issue by JakobBaum** [AbelHeinsbroek/chartjs-plugin-crosshair#107]
![download](https://user-images.githubusercontent.com/108228580/179194742-0b6d5c74-dc2c-499b-8905-57423762391c.png)
How do i get that little dot on the verticla line

**Comment by nategrift** [comment]
I am not sure what you mean by this as the intended use is to show a line where the graph and horizontal line connect. Gonna close this issue as it has become `stale`. Please open a new issue with more detail if you are still wanting a new issue
