### ISSUE TITLE
Disable and enable crosshair

### ISSUE THREAD

**Issue by yudomaryanto** [AbelHeinsbroek/chartjs-plugin-crosshair#124]
I have a button to enable and disable the crosshair, but I tried and couldn't make it work. Do you have any other suggestions?

This is my code for disable
Chart.options.plugins.crosshair = false;

Enable
Chart.options.plugins.crosshair = true;

**Comment by mattgatee** [comment]
To add to this, the documentation states pretty clearly [here](https://chartjs-plugin-crosshair.netlify.app/options.html) that `Chart.defaults.global.plugins.crosshair.*` turns off crosshairs globally, but there is no 'global' property for defaults.

For context, datalabels uses `Chart.defaults.plugins.datalabels.display = false;`
