### ISSUE TITLE
Disable crosshair for radar type charts. 

### ISSUE THREAD

**Issue by adrianamoni** [AbelHeinsbroek/chartjs-plugin-crosshair#16]
I've successfully implemented crosshair on two linear charts. My problem is that my app, needs lots of charts, some are not 'Line' type charts. And if I try to add a 'radar' type chart, my app crashes because crosshair is looking for xAxis and yAxis (that don't exist on a radar chart). So I need to disable crosshair for that specific chart. Can you tell me how to do it?

**Comment by adrianamoni** [comment]
Found the solution. You have to disable the plugin on the options parameter for that specific chart. e.g. 
 plugins: {
    crosshair: false
  },

**Comment by firebird631** [comment]
Never too late, but I have a solution. Set the color with #00000000 (black 100% transparent) and later set to another color #FF6666FF to show it back.
