### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by joseraul** [AbelHeinsbroek/chartjs-plugin-crosshair#32]
Hi!

Do you think would be possible to create a new release with the changes on master?
In fact, I saw that you already changed the version to 1.1.4.
I was going to create a PR adding support for `category` .. but is just there 😄 
https://github.com/AbelHeinsbroek/chartjs-plugin-crosshair/compare/v1.1.3...master#diff-1c7539eadace3d30f13b7c9ffcd868b9R47

Thanks!

**Comment by 4b11b4** [comment]
It would also be very helpful for me if a new release was created and pushed to npm registry after pull request #34 is merged! thanks for creating a great plugin

**Comment by AbelHeinsbroek** [comment]
Sorry! Due to a very nasty broken wrist and other priorities at work I've not been able to work on this plugin. I've merged 34 and updated the npm release!

**Comment by joseraul** [comment]
Thanks @AbelHeinsbroek
