### ISSUE TITLE
Time chart support?

### ISSUE THREAD

**Issue by benmccann** [AbelHeinsbroek/chartjs-plugin-crosshair#4]
I noticed that the samples are all linear axes. Does it work on time charts? The README doesn't say

**Comment by AbelHeinsbroek** [comment]
I does! I'm planning to add a time series example with zoom and dynamic load (for example stocks data) to the samples, for now you can find a working example on another project I'm working on:

https://vitens.github.io/pi-vue/charting.html#basic-charts

**Comment by benmccann** [comment]
That's great. The reason I was asking is because I'm working on https://github.com/chartjs/chartjs-chart-financial and thought this could be good plugin to use with it

**Comment by AbelHeinsbroek** [comment]
It seems to work ok, with some changes to the crosshair-plugin:

https://www.abelheinsbroek.nl/financial/

One issue I ran into is that scatter and line charts work with data.x to position data on the x axis, whereas your plugin uses data.t instead. Is there a specific reason for doing this?

Currently the plugin only works for scatter and line charts, I should change that to work for all charts with an Linear or Time x-axis.

**Comment by benmccann** [comment]
Very cool! I love it!

`t` is a more common way to express time than `x`, so the time scale supports input as `t` or `x`. If instead of doing `data.x` you do `scale.getRightValue(data)` it will work with `t` or `x`

**Comment by Dasheel** [comment]
New about this?

**Comment by Dasheel** [comment]
I got the crosshair plugin to work with the financial plugin by changing this line `(xScaleType !== 'linear' && xScaleType !== 'time')` to `(xScaleType !== 'linear' && xScaleType !== 'time' && xScaleType !== 'realtime'))` twice.

**Comment by AbelHeinsbroek** [comment]
You can right click and press view source on any webpage to view the source.

This file is what you're looking for I guess:

https://www.abelheinsbroek.nl/financial/index.js

**Comment by benmccann** [comment]
Adding `xScaleType !== 'realtime'` I believe would be adding support for the streaming plugin: https://github.com/nagix/chartjs-plugin-streaming/blob/master/src/scales/scale.realtime.js

**Comment by Dasheel** [comment]
> Adding `xScaleType !== 'realtime'` I believe would be adding support for the streaming plugin: https://github.com/nagix/chartjs-plugin-streaming/blob/master/src/scales/scale.realtime.js

Yes, adding this line would make the crosshair plugin support the streaming plugin but not for the crosshair zoom.
