### ISSUE TITLE
Release 1.1.5 missing dist folder

### ISSUE THREAD

**Issue by danmana** [AbelHeinsbroek/chartjs-plugin-crosshair#40]
The `dist` folder is missing in release 1.1.5, but package.json references
`"main": "dist/chartjs-plugin-crosshair.js",`

This causes imports to fail with `Module not found: Error: Can't resolve 'chartjs-plugin-crosshair'`

Version 1.1.4 contains the `dist` folder with `chartjs-plugin-crosshair.js` and `chartjs-plugin-crosshair.min.js` (as well as docs and samples)

**Comment by AbelHeinsbroek** [comment]
Wierd. Can you confirm that it's working with the latest version? 1.1.6

**Comment by danmana** [comment]
Yes, I can confirm, 1.1.6 has the dist folder and works.

Thanks
