### ISSUE TITLE
Possible to add a horizontal line to form a '+' cross?

### ISSUE THREAD

**Issue by Macscroge** [AbelHeinsbroek/chartjs-plugin-crosshair#41]
I tried doing this myself in the code but chart.crosshair.y is undefined so I can't seem to draw a line horizontally from the point. Am I missing something?

**Comment by AbelHeinsbroek** [comment]
It's not a feature by default, but should be relatively easy to implement:

add `chart.crosshair.y = e.y` here:
https://github.com/AbelHeinsbroek/chartjs-plugin-crosshair/blob/master/src/trace.js#L243

and update the drawTraceLine function to support y axis lines:
https://github.com/AbelHeinsbroek/chartjs-plugin-crosshair/blob/master/src/trace.js#L463

**Comment by Macscroge** [comment]
Fantastic thank you, that is all working nicely now.
Thanks for your help!

**Comment by davidyv** [comment]
Hi guys,

First, a big thanks for your awesome work, help.

I’m totally new to javascript, please forgive my ignorance. I have added the following code to line 243 of trace.js:

`chart.crosshair.y = e.y`

Then to update the drawTraceLine function:
```
drawTraceLine: function(chart) {

  var yScale = this.getYScale(chart);
  // for support y axis lines
  var xScale = this.getXScale(chart);
     
  var lineWidth = this.getOption(chart, 'line', 'width');
  var color = this.getOption(chart, 'line', 'color');
  var dashPattern = this.getOption(chart, 'line', 'dashPattern');
  var snapEnabled = this.getOption(chart, 'snap', 'enabled');

  var lineX = chart.crosshair.x;
  // for support y axis lines
  var lineY = chart.crosshair.y;

  var isHoverIntersectOff = chart.config.options.hover.intersect === false;

  if (snapEnabled && isHoverIntersectOff && chart.active.length) {
    lineX = chart.active[0]._view.x;
    // for support y axis lines
    lineY = chart.active[0]._view.y;
  }

  chart.ctx.beginPath();
  chart.ctx.setLineDash(dashPattern);
  chart.ctx.moveTo(lineX, yScale.getPixelForValue(yScale.max));
  // for support y axis lines
  chart.ctx.moveTo(lineY, xScale.getPixelForValue(xScale.max));

  chart.ctx.lineWidth = lineWidth;
  chart.ctx.strokeStyle = color;
  chart.ctx.lineTo(lineX, yScale.getPixelForValue(yScale.min));
  // for support y axis lines
  chart.ctx.lineTo(lineY, xScale.getPixelForValue(xScale.min));

  chart.ctx.stroke();
  chart.ctx.setLineDash([]);

},
```

But it’s not working.

I’d really appreciate any help.

**Comment by laurensV** [comment]
Could this be an option that you can turn on?

**Comment by jasperJNS** [comment]
> It's not a feature by default, but should be relatively easy to implement:
> 
> add `chart.crosshair.y = e.y` here: https://github.com/AbelHeinsbroek/chartjs-plugin-crosshair/blob/master/src/trace.js#L243
> 
> and update the drawTraceLine function to support y axis lines: https://github.com/AbelHeinsbroek/chartjs-plugin-crosshair/blob/master/src/trace.js#L463

How do I implement this? Do I clone repo and make an edited local version or something?

**Comment by guanzo** [comment]
How is this not a default option? It's not exactly a crosshair if there's no horizontal line..

Add this line to line 252: 

```js
chart.crosshair.y = e.y;
```

https://github.com/AbelHeinsbroek/chartjs-plugin-crosshair/blob/db69981a892d97bda5b36035ec5bd25cd99fddb2/src/trace.js#L251-L252

Updated `drawTraceLine` for the horizontal line:
```js
    drawTraceLine: function(chart) {
        var yScale = this.getYScale(chart);
        var xScale = this.getXScale(chart);

        var lineWidth = this.getOption(chart, 'line', 'width');
        var color = this.getOption(chart, 'line', 'color');
        var dashPattern = this.getOption(chart, 'line', 'dashPattern');
        var snapEnabled = this.getOption(chart, 'snap', 'enabled');

        var lineX = chart.crosshair.x;
        var lineY = chart.crosshair.y

        if (snapEnabled && chart._active.length) {
            lineX = chart._active[0].element.x;
        }

        // Draw vertical line
        chart.ctx.beginPath();
        chart.ctx.setLineDash(dashPattern);
        chart.ctx.moveTo(lineX, yScale.getPixelForValue(yScale.max));
        chart.ctx.lineWidth = lineWidth;
        chart.ctx.strokeStyle = color;
        chart.ctx.lineTo(lineX, yScale.getPixelForValue(yScale.min));
        chart.ctx.stroke();
        chart.ctx.setLineDash([]);

        // Draw horizontal line
        chart.ctx.beginPath();
        chart.ctx.setLineDash(dashPattern);
        chart.ctx.moveTo(xScale.getPixelForValue(xScale.max), lineY);
        chart.ctx.lineWidth = lineWidth;
        chart.ctx.strokeStyle = color;
        chart.ctx.lineTo(xScale.getPixelForValue(xScale.min), lineY);
        chart.ctx.stroke();
        chart.ctx.setLineDash([]);
    },
 ```
