### ISSUE TITLE
Linked Charts without linked Legends

### ISSUE THREAD

**Issue by sheixt** [AbelHeinsbroek/chartjs-plugin-crosshair#45]
It is possible to create linked charts but to remove the functionality that links the legends?

I've created a simple example of linked charts (loosely based around one of the samples): https://codepen.io/sheixt/pen/JjGvbVJ

As you can see, if you "turn off" a dataset (e.g. Dataset 1, "A" in chart 1,  "D" in chart 2, and "G" in chart 3), the dataset is removed from all of the linked charts.

I have a series of charts that are based on the same x-axis data so the crosshair line & the tooltip appearing on all of the linked charts is ideal. But as each dataset that is plotted is not the same across the various charts, I do not want it to disappear on click.

So in my example deselecting Dataset 1 on chart A, that would be removed but  "D" in chart 2, and "G" in chart 3 should remain. I couldn't see specification for this in the documentation. 

I hope this is the right place to raise such a query. Let me know if I can offer any further information.

(If this isn't possible, could point me to the section of the plugin that handles this? Then I shall see if I can offer PR with a solution.)

**Comment by leeoniya** [comment]
@sheixt 

since this repo appears to be fairly dormant in terms of maintenance, i'll plug [uPlot](https://github.com/leeoniya/uPlot), which can sync cursors without syncing legend toggle: https://jsfiddle.net/Lkj13e7t/. if you ever need the legend-toggle synced, set `cursor.sync.setSeries: true`.

**Comment by sheixt** [comment]
@leeoniya thank you for letting me know about uPlot, I'm already very engrained with chart-js now so moving the entire projects charting dependency

**Comment by danmana** [comment]
@sheixt I recently had a use for this, so I implemented it.

Until the PR is merged, you can use [patch-package](https://www.npmjs.com/package/patch-package) to implement it as a patch directly in node_modules.
