### ISSUE TITLE
Property "register" undefined?

### ISSUE THREAD

**Issue by Creatium** [AbelHeinsbroek/chartjs-plugin-crosshair#75]
Hi,

Trying to use this plugin. I have two charts that are loaded via AJAX call for data. The problem is that when used with Chart JS 3.2.0 I get this error in Console and plugin does not work:

```
chartjs-plugin-crosshair@1:7 Uncaught TypeError: Cannot read property 'register' of undefined
    at chartjs-plugin-crosshair@1:7
    at chartjs-plugin-crosshair@1:7
    at chartjs-plugin-crosshair@1:7
    at chartjs-plugin-crosshair@1:7
```

**Comment by vhphan** [comment]
Does it work with Chart JS >= 3 at all?

**Comment by bruderDima** [comment]
I have the same problem. 
chartjs-plugin-crosshair@1:7 Uncaught TypeError: Cannot read property 'register' of undefined
    at chartjs-plugin-crosshair@1:7
    at chartjs-plugin-crosshair@1:7
    at chartjs-plugin-crosshair@1:7
    at chartjs-plugin-crosshair@1:7

How i can fix it ?

**Comment by definitelynottitus** [comment]
basically, this plugin does not work on any version above v3 as there was a big migration from chart js. But the way to fix the problem is to change Chart.plugins.register(crosshairPlugin); to Chart.register(crosshairPlugin); but this will create other issues which I am currently working on to ressolve.

**Comment by AbelHeinsbroek** [comment]
I've started a chartjs3 branch to work on chartjs3.4 compatibility. Could you check if that version works for you?

**Comment by vincepolston** [comment]
Great work! I just built the version from chartjs3 branch and confirmed it works with ChartJS 3.4.0.
