### ISSUE TITLE
Docs website is not working

### ISSUE THREAD

**Issue by filingroove** [AbelHeinsbroek/chartjs-plugin-crosshair#9]
It'll be nice to see the docs :) Mb you haven't noticed

**Comment by 4lyn** [comment]
Hi,

The website is still down :disappointed:

**Comment by pratikdhavale** [comment]
Hi 

Doc urls are not working
[https://chartjs-plugin-crosshair.netlify.com/installation](url)
[https://chartjs-plugin-crosshair.netlify.com/options](url)

**Comment by AbelHeinsbroek** [comment]
Docs are up
