### ISSUE TITLE
Is this plugin alive?

### ISSUE THREAD

**Issue by fairking** [AbelHeinsbroek/chartjs-plugin-crosshair#94]
I cannot see any progress since July. Is there any contributers who can push pending PRs forward?
The plugin is not compatible with the latest Chartjs. It is only working with Chartjs v3.4.0

**Comment by geriatricdan** [comment]
Apparently not. There are tons of errors with chartjs v3.4.0+. Literally incapable of updating my versions. Trying to use 1.2 with any of the new versions breaks.

**Comment by nategrift** [comment]
Plugin is still alive, support for Chartjs v4 is now available with latest version of this plugin `v2.0.0`. If you are having a specific issue, please create an issue with details regarding it.
